{% set name = "django-constance" %}
{% set version = "3.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2b96e51de63751ef63f8f92f74e0f6aea30fb6453f3a736c21e1f8b3f6cf0b4f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - django
  run:
    - python
    - setuptools
    - django

about:
  home: "https://github.com/jazzband/django-constance"
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "Django live settings with pluggable backends, including Redis."
  doc_url: https://django-constance.readthedocs.io/
  dev_url: https://github.com/jazzband/django-constance

extra:
  recipe-maintainers:
    - https://github.com/gb119
